name: Pre-commit checks
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]  # run when pushing to main
  pull_request:
    branches: [main]  # run on PRs targeting main
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.15"
          enable-cache: true

      - name: Setup pre-commit cache
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-3-${{ runner.os }}-
            pre-commit-3-

      - name: Configure SKIP for pre-commit hooks
        run: echo "SKIP=no-commit-to-branch" >> "$GITHUB_ENV"

      - name: Run pre-commit using uvx
        run: uvx --with pre-commit-uv pre-commit run --all-files
        env:
          SKIP: ${{ env.SKIP }}
